server:
  port: 8088

spring:
  application:
    name: json-to-sql-translator

logging:
  level:
    com.example.jsontosql: DEBUG
    org.apache.calcite: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always